### ISSUE TITLE
Operator API - support LineString?

### ISSUE THREAD

**Issue by issmith1** [nasa/utm-apis#122]
Should TCL4 continue to support LineString?  
I understand that trajectory flight plans can be modeled as a list of small volumes.

**Comment by nasajoey** [comment]
The commons models do not support linestring.  I think NUSS only needs this if there is some value to the clients we support.  If we want to reduce NUSS complexity at the cost of increasing client complexity, then we can drop the support.

I think the Python client creates the volumes, so that complexity is already in one of our clients.  Not sure how AOL is handling it now for MACS integration?  If they don't need linestring, we probably can drop it.

Please correct me or add more context if needed.  Very possible I am missing the key issues.

**Comment by issmith1** [comment]
that captures it.  I will propose removal to the Operator API stakeholders.
