### ISSUE TITLE
uss_name vs. originator_id

### ISSUE THREAD

**Issue by shabemdadi** [nasa/utm-apis#134]
I noticed that in some models (UtmMessage, UasVolumeReservation) we are using originator_id, defined as:

> A name identifying the originator   of this message. If a USS is the originator, then this field MUST be   the uss_name as known by the authorization server. The maximum   and minimum character length is based on a usable domain name, and   considering the maximum in RFC-1035.

While in other models (UssInstance, Operation, and Position) we are using uss_name, defined as:

> The name of the entity providing UAS Support Services. Populated by the service discovery system based on credential information provided by the USS. The maximum and minimum   character length is based on a usable domain name, and considering   the maximum in RFC-1035.

These seem like they are the same thing, if so, maybe we should pick one and make it consistent across.

**Comment by nasajoey** [comment]
The issue with UTMMessage and UVRs is that they may or may not be generated by a USS.  Thus the field "uss_name" is not always appropriate.  This is why in those models there is an "origin" field... if origin == USS, then originator_id is equivalent to uss_name.  originator_id was such a clunky label, I didn't originally want it in all the models.

I'm open to suggestions on how to fix this because I agree that it is not elegant and that consistency is preferred.  We can change them all to originator_id or if you have a better suggestion, please let me know.

Would appreciate any other thoughts by folks too.

**Comment by nasajoey** [comment]
I like consistency.  Open to having FIMS have a "uss_name" since it is used within the USS Network.

**Comment by nasajoey** [comment]
Alright... going to close out.  If I missed any references or there are further changes, should open a new issue.
