### ISSUE TITLE
The size range for uss_name is not consistent

### ISSUE THREAD

**Issue by HarryAirMap** [nasa/utm-apis#151]
There are fields like uss_name, uss_name_of_originator, and uss_name_of_receiver.

At some places their range is [1,250], but at some other places their range is [4, 250].

It is better to make them consistent.

**Comment by nasajoey** [comment]
the correct range is [4,250] going off the minimum length of a valid DNS name.  something like:

`a.co` or `c.at` are as short as allowed by DNS specs I think.  So 4 chars is the correct min.

Trick is finding them all in the various API docs.  If anyone sees specific ones, feel free to note them in this ticket.

**Comment by issmith1** [comment]
Joey,Our main question is,  technically this is breaking change.  
BUT its highly unlikely going to break in reality.  Thus may we fix it now rather than managing with another sprint/cycle of API changes?

**Comment by nasajoey** [comment]
fix it now, I'd say.  the only way it truly breaks someone is if a USS provides a DNS name less than 4 characters... since we know we have no valid USS names of size less than 4 (and never will), they would fail anyway due to invalid creds.  I think this one is safe to change at any time we choose.  Will leave the timing to you.

**Comment by utmnasa** [comment]
c4cfa67ea32dbac7db23a6a21867a3eae577966e
domain file
