### ISSUE TITLE
uss_id not a property of Operation

### ISSUE THREAD

**Issue by shortwavedave** [nasa/utm-apis#168]
In the USS api spec, for a put on '/operations/{gufi}', there is the note:

https://github.com/nasa/utm-apis/blob/f415e12f67c71e3aaaaec7dffa5a3838f0cf693d/uss-api/swagger.yaml#L602

However, there is no uss_id property defined in the Operation object in utm-domain-commons.yaml
https://github.com/nasa/utm-apis/blob/f415e12f67c71e3aaaaec7dffa5a3838f0cf693d/utm-domains/utm-domain-commons.yaml#L338

Have I reconciled this note correctly? What is uss_id in reference to?

**Comment by nasajoey** [comment]
Looks like a typo. 

Instead of 
`Operation.uss_id == access_token.sub`

We should have 
`Operation.uss_name == access_token.sub` 
in order to match the definition in commons.  

Thanks for the links... I used them to check this quickly.  If my answer doesn't make sense or if you think I may have mis-stated something, please follow up.

**Comment by shortwavedave** [comment]
Thanks @nasajoey I submitted a pull request, so I'll close this issue
