### ISSUE TITLE
Define validation rules for Position and UTMMessage 'time*' fields compared to 'now'

### ISSUE THREAD

**Issue by punamverma** [nasa/utm-apis#19]
What happens when time_sent is after current time for the receiving USS, which is related to time sync between USSes. Do we need to have validation?

**Comment by nasajoey** [comment]
Due to lack of definition for time synchronization amongst USSs, the receiving USS should not reject based on potential discrepancies between local clock and timestamps received from other USSs.

The only time checks (I think) should be to ensure consistency amongst the timestamps within the full model as received.  So, start time for an operation should be before the end time, for example.  And for positions, the time measured should be before time sent for example.  But if time sent is a second later than the receiving USS's clock, the data should still be accepted as valid.

In that case where there is detected clock skew or clock sync issues, I think we should have some mechanism to alert appropriate systems to that fact.  That is a separate discussion.

**Comment by nasajoey** [comment]
Closing this as "done" given that I got a single thumbs up on my previous comment.  The comment will be law.  Will have to be documented in USS Spec as this is tricky to fully describe just in API documentation.
