### ISSUE TITLE
Operation user_id max length unspecified

### ISSUE THREAD

**Issue by esparano** [nasa/utm-apis#24]
The Operation model, as seen in the USS required API /operations/{gufi} endpoint https://app.swaggerhub.com/apis/utm/uss/v3#/A.%20Required%20Endpoints/put_operations__gufi_
specifies a maxLength of 100 for the created_by field, but does not specify a maxLength for the user_id field even though these fields seem to be similar.

I would expect their maxLength to be the same unless I'm missing something.

**Comment by nasajoey** [comment]
user_id field is slated for deprecation and has probably been neglected in the documentation.  Actually, I'm not clear on the future or "created_by" at this point either.  Some of these go away due to the improved authentication/authorization approach being implemented moving forward.

Thanks for the catch on this.  Please feel free to point out any of these issues.

I'm going to keep this issue open until we either get rid of that field or improve the validation for maxLength.

**Comment by nasajoey** [comment]
@punamverma , @issmith1 , @myspri :  can you comment on this one?  I think we should be removing user_id and created_by.  Is there some use that I am forgetting?  Some dependency that makes this a bad idea?

**Comment by punamverma** [comment]
@nasajoey: I am not sure about the need for these two fields, but I do see that operator operation has both of these fields, could have been carried over from there. From operator api, I found this -

created_by | stringThe user that created the operation. It is possible that an operation is created on behalf of an operator by, say, a manager. Nominally, this field will be equal to user_id.
-- | --

user_id* | stringThis field is populated based on provided credentials in the HTTPS header.
-- | --

@issmith1 @myspri might have a better idea about it.

**Comment by nasajoey** [comment]
Eliminated both fields, created_by and user_id from Operation model.
