### ISSUE TITLE
time_available_end requirement for put operation 

### ISSUE THREAD

**Issue by ktian94** [nasa/utm-apis#61]
In the uss api spec for [PUT operation](https://github.com/nasa/utm-apis/blob/26bfad924ae9a902cea03c61c6a807fe57645762/uss-api/swagger.yaml#L506), it mentions that the time_available_end should be in the future. Could we get clarification on this as there's no time_available_end field in operation? Should this refer to effective_time_begin and effective_time_end for operation volumes?

**Comment by myspri** [comment]
It could be that you are referring to an older version of the API
Please use this 
https://github.com/nasa/utm-apis/blob/v4-draft/uss-api/swagger.yaml or the corresponding tagged version.

 effective_time_begin and effective_time_end should be related to operation volumes.

**Comment by myspri** [comment]
@nasajoey, the description in L522 in the Swagger needs to be updated.

**Comment by myspri** [comment]
Posting on behalf of @ktian94 
"Are we supposed to validate that both are in the future for every operation volume when an operation is first constructed?"

**Comment by ktian94** [comment]
Is there any update here? Is it a requirement that for every new operations created, every operation volume's effective_time_begin and effective_time_end should be in the future? 

Just want to make sure in case this is in your Sprint 0 testing plan :)

**Comment by nasajoey** [comment]
Due to the fact that we haven't finalized a time synchronization spec for USSs, we've relaxed the "in the future" requirement for now.  We've seen operational problems when servers between orgs are not time synched so each server's view of what is in the future and what is in the past caused plan rejections.  So, long story only slightly longer, no requirement on "future", but please don't actively abuse the lack of check.  We are in the "please" and "thank you" phase of UTM development.  When we nail down time sync issues, this requirement will come back.

**Comment by nasajoey** [comment]
Going to close this one out.
