### ISSUE TITLE
Operation EventMetadata: Now Required?

### ISSUE THREAD

**Issue by jfisherge** [nasa/utm-apis#84]
One of the changes from TCL3 to TCl4 APIs is the requirement to have an ```EventMetadata``` object always sent/received within each ```Operation```. I'm curious as to why this specific property is now a requirement. My understanding based on the ```EventMetadata``` object model properties (e.g. testCard, testType, testSetting, isDataCollection, etc.) is that this model is for TCL-specific tests. Right now, given the requirement on the ```Operation``` model, this will have to be set, and it's not clear what the default values should be outside of a specific test scenario. I'm currently setting these to bogus values (e.g. eventId: "not_set"), which is not a satisfying fix. Please advise. Thanks!

**Comment by nasajoey** [comment]
They are indeed testing specific data in the EventMetadata model.  In TCL3 we had this as "optional" in the API since it doesn't represent data that are going to be in the future system, but were "required" for testing.  This was confusing as some implementers didn't implement due to the API documentation, and that caused problems for data collection.

So, yes it is required to implement and test.  For now you can put dummy data.  For future tests, we will provide guidance for the appropriate data to populate.

**Comment by nasajoey** [comment]
Since I got @jfisherge thumbs up on previous post, going to close this one.  Please comment if we should discuss further.
