### ISSUE TITLE
Order of OperationVolumes with respect to Start and End Times

### ISSUE THREAD

**Issue by shabemdadi** [nasa/utm-apis#90]
It seems as though the list of operation volumes within the Operation model should be in sequential order (the first volume in the list has the _earliest start time_ of all others in the list), however, I am curious if we can assume that the last volume in the list has the _latest end time_ of all others in the list as well.

I am thinking of a case where we have:
[0] - 1-8
[1]- 2-6

Where the earlier starting volume consumes and extends over the period of the second volume. Could this/should this be possible?

**Comment by nasajoey** [comment]
Thanks for opening this discussion.

Looking at the JSON RFC spec, it says that

> An object is an **unordered** collection of zero or more name/value
>    pairs, where a name is a string and a value is a string, number,
>    boolean, null, object, or array.

And then it says that 

>An array is an **ordered** sequence of zero or more values.

So I think your point is reasonable given that arrays are indeed to be interpreted as ordered.  Will have to work on the language a little since some folks may have operation volumes with equal end times.  Probably best to order by `ordinal` data element.

**Comment by nasajoey** [comment]
I defer to an RFC whenever possible.  For reference, the JSON RFC: https://tools.ietf.org/html/rfc8259

**Comment by boguwei** [comment]
If we order on ordinal, it doesn't preclude @shabemdadi 's point right? should we enforce traversal of volumes by ordinal (i.e. no back tracking), or is it a valid use case to go from volume 0 to volume 1, and then back to volume 0 (using the example given in the original post).

**Comment by nasajoey** [comment]
Sorry if I didn't take in the details in the original post.  I didn't see the weird end times.

@boguwei you are correct that ordering the JSON doesn't preclude @shabemdadi 's point.  The validation rules for opvols as currently written are also not violated by this case.

As a USS, you work to ensure your operators stay conforming.  An op is geo-conforming (not a real term) if their current position is 4-D within at least one of their operation volumes.  So the "backtracking" is possible, but maybe it shouldn't be?  That is the main question on the table it seems.

We had a detailed discussion (#14) to reach the current validation rules for operation volumes, but I don't think the discussion considered @shabemdadi 's case. Her case satisfies the validation rules, so I'd have to say we accept it unless there is a strong reason not to.  Note that understandability and intuition may actually be strong reasons to not allow the highlighted case.

Given his input on the previous discussion, I'll tag in @esparano to hear his thoughts.

Happy to hear more thoughts on this from anyone.  My default position is to do nothing and say this passes our validation rules, so we leave it as "legal".  My mind can be changed.

**Comment by esparano** [comment]
I must admit that I don't totally understand Operation Volumes, even after reading some of the specs. The old USS Specification states that 

> At any given time, an operation is expected to be contained within _at least one_ valid Conformance Volume. 

The Swaggerhub Docs also indicate that 

> Providing multiple uas_registrations ... implies that all vehicles will conform to the provided operation volumes.

Does that mean that, if you have two vehicles, they must follow roughly the same path through the operation volumes? Or can their paths diverge so that there are eventually multiple simultaneous operation volumes that don't intersect spatially? For example: 
![image](https://user-images.githubusercontent.com/3947139/43209870-b9d27ab0-8ffb-11e8-867c-943ef718227d.png)

If this is a valid operation, that would be relevant to this question because then we cannot have any restrictions on the start and end times. That would complicate things a lot.

Either way, the current validation of operation volumes is **insufficient to guarantee that they are navigable**. The only restriction that we seem to have is that consecutive operation volumes must, as a pair, be navigable, meaning that there exists some 4D path from the first to the second volume. That implies that there is an overlap in at least 3 dimensions of space/time. However, that rule alone can lead to situations where the overall set of operation volumes is not navigable. For example:
![image](https://user-images.githubusercontent.com/3947139/43210547-6aaaa1c2-8ffd-11e8-9185-a4f46fffe195.png)

Each pair of consecutive operation volumes has a 4D overlap, but the path still isn't navigable because we do not travel backwards in time :) 

Sorry if I only asked more questions than I helped answer!

**Comment by nasajoey** [comment]
Thanks for the thoughts @esparano .

in your diagrams, we are only saved by your quote of the USS Spec:

> At any given time, an operation is expected to be contained within at least one valid Conformance Volume.

If the operation can't actually navigate the plan, then they are going to break spec if they try.

The easiest fix I can think of right now is to require that start time of a preceding volume must be before (or equal to?) start time of succeeding volume (ordered by opvol.ordinal).  Would this make most problems listed here go away?  Does that harm any key business cases?

As for the multiple vehicle question, i will table that for now.  It is on-going research to determine how to handle formations and swarms.  The diagram or split trajectories you provide is a good one to illustrate cases to watch out for, thanks.  Will probably need a requirement that all vehicles in swarm/formation share an opvol at all times or something.  but, don't want to sidetrack this opvol time discussion right now.

**Comment by boguwei** [comment]
> If the operation can't actually navigate the plan, then they are going to break spec if they try.

You don't necessarily need to break spec on the second diagram though unless you are required to utilize all the operation volumes you filed? To separate out the intention of the operation from the actual filed model of it, an operation can simply end in volumes 3 or 4 (while still being in a valid conformance volume). Such a filing would not break validation, but would conflict with anybody who will intersect with vol. 5 (even though the original operator can't possibly use it).

**Comment by boguwei** [comment]
> The easiest fix I can think of right now is to require that start time of a preceding volume must be before (or equal to?) start time of succeeding volume (ordered by opvol.ordinal).
+1 on this.

**Comment by nasajoey** [comment]
I think some of this comes down to how we end up measuring efficiency of planning by USSs and Operators.  I think there will always be ways to create extraneous operation volumes that pass the validation rules.  we'll need incentives toward efficiency, which is a separate discussion.

So, with the assumption that everyone WANTS efficient plans (or have been coerced into wanting them), I think the additional check I proposed (start times are non-decreasing) solves more probs than it creates.

Agreement?  Counterpoints?

**Comment by esparano** [comment]
> I think there will always be ways to create extraneous operation volumes that pass the validation rules. we'll need incentives toward efficiency, which is a separate discussion.
I strongly agree with this. I'm still thinking of edge cases but perhaps I should accept that there is no simple set of rules that will guarantee efficiency without being too restrictive. So I'd rather be less restrictive and then ensure efficiency in another way. 

So, I agree with your solution, Joey, but I don't think we've fully or clearly answered the original question. 

I do think that backtracking (going back to a previous volume) is a valid use case. But the USS could also just create another operation volume if they want to. Therefore, maybe we can also assume end-times are non-decreasing and disallow backtracking after all. For example:
![image](https://user-images.githubusercontent.com/3947139/43218115-7ecd712a-9011-11e8-9162-f04c03f4d90c.png)
This fails because 2 and 3 aren't overlapping, even though it's a perfectly reasonable use case. So the USS could instead submit these volumes: 
![image](https://user-images.githubusercontent.com/3947139/43218168-9f7ddf40-9011-11e8-8ed2-9b49c0e141a1.png)
And this would pass validation and have nondecreasing start and end times... Thoughts?

**Comment by nasajoey** [comment]
i don't disagree with any of you points, except that I am cautious to closing off use cases we haven't fully explored yet to solve what may be not a huge problem in practice.

The main case I have in mind is a tall, narrow, vertical land/launch volume that gets someone up to a mission volume where they do some stuff and then come back to use the land/launch volume again.  They could keep that initial volume open the whole time and have that operation volume at altitude only open for a subset of that time.  Granted this isn't the most efficient as you could do this with 3 volumes (the first tow being spatially equivalent), but this may come at the cost of planning complexity and it might not usually have any effect on other airspace users.

Anyway, that is why I am cautious about adding the end time rule you suggest.  Still, I'm open to further persuasion.  Feel free to poke holes in my comments.

**Comment by esparano** [comment]
Yeah, I agree. I'm cautious about it too. Perhaps it's easier/safer to add more restrictions later.

**Comment by nasajoey** [comment]
I feel like I want to continue the conversation just so I can get some more of @esparano 's colorful spatial-temporal charts!
